name: Deploy to EC2

on:
  push:
    branches:
      - main  # Runs the workflow whenever there's a push to the 'main' branch.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository to get the code
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to EC2
      run: |
        pwd
        ls
        chmod 600 private-key.pem
        ssh -o StrictHostKeyChecking=no -i /home/runner/work/deploy/deploy/private-key.pem ubuntu@98.84.144.56
