name: Deploy to EC2

on:
  push:
    branches:
      - main  # Runs the workflow whenever there's a push to the 'main' branch.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository to get the code
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        pwd
        ls
        echo $PRIVATE_KEY
        ssh -i $PRIVATE_KEY $HOST@$USER 
  
